version: '3.8'
services:
  secrets-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
